import { AllProducts } from "./types";
import Imagen from '../../assets/img/product-img.jpg'

export const productList: AllProducts = {
  premium: [
    {
      name: 'Pantera Rosa',
      category: 'premium',
      descrption: 'Descripcion larga del producto Pantera Rosa qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de Pantera Rosa',
      hasMint: true,
      flavor: 'frutal',
      img: Imagen,
      soldOut: false,
      isNew: false,
    },
    {
      name: 'Tony Montana',
      category: 'premium',
      descrption: 'Descripcion larga del producto Tony Montana qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de Tony Montana',
      hasMint: false,
      flavor: 'tabaquil',
      img: Imagen,
      soldOut: false,
      isNew: false,
    },
  ],
  tradicional: [
    {
      name: 'Tormenta',
      category: 'tradicional',
      descrption: 'Descripcion larga del producto Tormenta qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de Tormenta',
      hasMint: true,
      flavor: 'frutal',
      img: Imagen,
      soldOut: true,
      isNew: false,
    },
    {
      name: 'Freezer',
      category: 'tradicional',
      descrption: 'Descripcion larga del producto Freezer qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de Freezer',
      hasMint: false,
      flavor: 'mentolado',
      img: Imagen,
      soldOut: false,
      isNew: false,
    },
  ],
  lowCost: [
    {
      name: 'Uva',
      category: 'lowCost',
      descrption: 'Descripcion larga del producto Uva qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de Uva',
      hasMint: false,
      flavor: 'frutal',
      img: Imagen,
      soldOut: true,
      isNew: false,
    },
    {
      name: 'Cafe con Crema',
      category: 'lowCost',
      descrption: 'Descripcion larga del producto Cafe con Crema qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de Cafe con Crema',
      hasMint: false,
      flavor: 'postre',
      img: Imagen,
      soldOut: false,
      isNew: false,
    },
  ],
  salt: [
    {
      name: 'Woody',
      category: 'salt',
      descrption: 'Descripcion larga del producto Woody qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de Woody',
      hasMint: false,
      flavor: 'frutal',
      img: Imagen,
      soldOut: false,
      isNew: false,
    },
    {
      name: 'El Padrino',
      category: 'salt',
      descrption: 'Descripcion larga del producto El Padrino qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de El Padrino',
      hasMint: false,
      flavor: 'tabaquil',
      img: Imagen,
      soldOut: false,
      isNew: false,
    },
  ],
  insumos: [
    {
      name: 'Baterias Samsung Q30',
      category: 'insumos',
      descrption: 'Descripcion larga del producto Baterias Samsung Q30 qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de Baterias Samsung Q30',
      img: Imagen,
      soldOut: false,
      isNew: true,
    },
    {
      name: 'Pirex plastico',
      category: 'insumos',
      descrption: 'Descripcion larga del producto Pirex plastico qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de Pirex plastico',
      img: Imagen,
      soldOut: false,
      isNew: false,
    },
  ],
  equipos: [
    {
      name: 'DRAG 3 TPP-X - KIT',
      category: 'equipos',
      descrption: 'Descripcion larga del producto DRAG 3 TPP-X - KIT qu ese usa dentro del modal donde se realiza el pedido. Tambien incluye la receta y nota sobre procedencia de la materia prima.',
      shortDesc: 'Descripcion corta de DRAG 3 TPP-X - KIT',
      img: Imagen,
      soldOut: false,
      isNew: true,
    },
  ],
}
